"""fourth migration

Revision ID: 2de18401c222
Revises: ac415edb6a16
Create Date: 2021-11-29 10:15:16.886602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de18401c222'
down_revision = 'ac415edb6a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_address',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], )
    )
    op.create_table('contact_email',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], )
    )
    op.create_table('contact_phone',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.id'], )
    )
    op.drop_table('note')
    op.add_column('contact', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('contact', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('contact', 'email')
    op.drop_column('contact', 'name')
    op.drop_column('contact', 'phone')
    op.drop_column('contact', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contact', 'last_name')
    op.drop_column('contact', 'first_name')
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='note_pkey')
    )
    op.drop_table('contact_phone')
    op.drop_table('contact_email')
    op.drop_table('contact_address')
    op.drop_table('phone')
    op.drop_table('email')
    op.drop_table('address')
    # ### end Alembic commands ###
