"""First migration

Revision ID: 809872e0b2a0
Revises: 
Create Date: 2021-11-23 13:43:04.341659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809872e0b2a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_note', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('text_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('contact')
    # ### end Alembic commands ###
