"""second migration

Revision ID: 8ec50a452925
Revises: 809872e0b2a0
Create Date: 2021-11-29 09:52:06.267838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec50a452925'
down_revision = '809872e0b2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
