"""third migration

Revision ID: ac415edb6a16
Revises: 8ec50a452925
Create Date: 2021-11-29 09:55:56.345765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac415edb6a16'
down_revision = '8ec50a452925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
