# Generated by Django 4.0 on 2022-01-04 12:24

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateField(default=finance.models._default_date, verbose_name='Created timestamp'),
        ),
    ]
